# -*- coding: utf-8 -*-
"""Bandlet Transform Smoke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5qf_RMH-DbP98jMLuQycOobW8InlG4e
"""

import os, sys, shutil, subprocess

REPO_URL = "https://github.com/AngshulMajumdar/Bandlet-Transform-API.git"
REPO_DIR = "/content/Bandlet-Transform-API"

if os.path.exists(REPO_DIR):
    shutil.rmtree(REPO_DIR)

subprocess.run(["git", "clone", REPO_URL, REPO_DIR], check=True)
os.chdir(REPO_DIR)

subprocess.run([sys.executable, "-m", "pip", "install", "-e", "."], check=True)
subprocess.run([sys.executable, "examples/smoke_test.py"], check=True)
subprocess.run([sys.executable, "-m", "pytest", "-q"], check=True)

# TEST 1: encode_packed -> decode_packed round trip

import torch
from bandlet_tf import BandletTransform

device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.randn(2, 1, 64, 64, device=device)
bt = BandletTransform().to(device)

packed, meta = bt.encode_packed(x)
x_hat = bt.decode_packed(packed, meta)

rel_err = (x - x_hat).norm().item() / (x.norm().item() + 1e-12)
max_abs = (x - x_hat).abs().max().item()
mse = ((x - x_hat) ** 2).mean().item()

print("packed shape:", tuple(packed.shape))
print("relative error:", rel_err)
print("max abs error:", max_abs)
print("mse:", mse)

# TEST 2: CPU vs CUDA parity

import torch
from bandlet_tf import BandletTransform

assert torch.cuda.is_available(), "CUDA not available"

x_cpu = torch.randn(1, 1, 64, 64)
x_gpu = x_cpu.cuda()

bt_cpu = BandletTransform().cpu()
bt_gpu = BandletTransform().cuda()

c_cpu = bt_cpu.encode(x_cpu)
c_gpu = bt_gpu.encode(x_gpu)

xhat_cpu = bt_cpu.reconstruct(c_cpu).detach().cpu()
xhat_gpu = bt_gpu.reconstruct(c_gpu).detach().cpu()

diff = (xhat_cpu - xhat_gpu).abs()
print("cpu/gpu recon max abs diff:", diff.max().item())
print("cpu/gpu recon mse:", (diff**2).mean().item())

# TEST 3: real-image smoke test from skimage

import torch
import matplotlib.pyplot as plt
from skimage import data, transform
from bandlet_tf import BandletTransform

device = "cuda" if torch.cuda.is_available() else "cpu"

img = data.camera()  # uint8, 512x512
img = transform.resize(img, (64, 64), anti_aliasing=True)
x = torch.tensor(img, dtype=torch.float32).unsqueeze(0).unsqueeze(0).to(device)

bt = BandletTransform().to(device)
coeffs = bt.encode(x)
x_hat = bt.reconstruct(coeffs)

rel_err = (x - x_hat).norm().item() / (x.norm().item() + 1e-12)
max_abs = (x - x_hat).abs().max().item()
mse = ((x - x_hat) ** 2).mean().item()

print("relative error:", rel_err)
print("max abs error:", max_abs)
print("mse:", mse)

plt.figure(figsize=(10,3))

plt.subplot(1,3,1)
plt.imshow(x[0,0].detach().cpu(), cmap="gray")
plt.title("input")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(x_hat[0,0].detach().cpu(), cmap="gray")
plt.title("reconstruction")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow((x[0,0]-x_hat[0,0]).abs().detach().cpu(), cmap="gray")
plt.title("abs error")
plt.axis("off")

plt.tight_layout()
plt.show()